# #Docker Compose version v2.38.2

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx42
    env_file:
      - .env
    networks:
      - inception
    # This policy restarts the container automatically if it stops for any reason, except when you intentionally stop it with docker stop.
    # restart: unless-stopped
    #"<host_port>:<container_port>" :port mapping configuration. It instructs Docker to forward network traffic from the host machine to the container.
    # need to mount for searching the index.php (:ro is read only)
    volumes:
      - wp_volume:/var/www42/html42:ro
    ports:
      - "443:443"
      # depends_on sets startup order between services.
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress42
    env_file:
      - .env
    networks:
      - inception
    # restart: unless-stopped
    # volume(sourse) : target(container)
    volumes:
      - wp_volume:/var/www42/html42
    # !!depends_on does not wait until the database is ready
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb42
    env_file:
      - .env
    networks:
      - inception
    # restart: unless-stopped
    # volume(sourse) : target(container)
    volumes:
      - db_volume:/var/lib/mysql

# opts & o: option
volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oyuhi/data/wp_volume

  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oyuhi/data/db_volume

# networks: inception: at the bottom is just the definition of the network
networks:
  inception:
    driver: bridge

# driver: bridge : creates a private virtual LAN where your containers can talk to each other by service name.
